### ISSUE TITLE
[Freelancer] medic appointement for direcuts v9.

### ISSUE THREAD

**Issue by hermesalvesbr** [hairmare/directus-extension-interface-recurringrule#5]
Hi

I'm looking for a custom extension for medic appointement for direcuts v9. 

**Features**
1 Select the doctor (load the avaliable dates)
2 Show by color in the date picker the avaliable dates
3 Schedule an appointment choosing the free hours
4 Validate for date/hour conflicts.

**SAMPLE:**
![166241874-bd89e5ef-07c8-4fa4-84d7-a77ff18999c8](https://user-images.githubusercontent.com/379850/166673114-6f98733e-2dea-49df-9723-cc70b0bcc402.png)

Do you have avaliability for this freelancer?

**Comment by hairmare** [comment]
Thanks for the interest, I currently don't do freelance work.
